import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { EmailService } from '../services/email.service';

@Injectable()
export class ForensicAlertJob {
  private readonly logger = new Logger(ForensicAlertJob.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly email: EmailService,
  ) {}

  /** Run every hour */
  @Cron('0 * * * *', { name: 'forensic-alert' })
  async handle() {
    this.logger.log({ job: 'ForensicAlertJob' }, 'Starting forensic alert job');
    const start = Date.now();

    try {
      const suspects = await this.prisma.$queryRaw<
        Array<{
          mobile_number: string;
          tx_count: number;
          first_tx_date: Date;
          last_tx_date: Date;
          stores: string[];
          total_amount: number;
        }>
      >`
        SELECT 
          c.country_code || c.mobile_number as mobile_number,
          COUNT(t.id)::int as tx_count,
          MIN(t.transaction_date) as first_tx_date,
          MAX(t.transaction_date) as last_tx_date,
          ARRAY_AGG(DISTINCT t.store) FILTER (WHERE t.store IS NOT NULL) as stores,
          SUM(t.sale_amount)::float as total_amount
        FROM transactions t
        JOIN customers c ON c.id = t.customer_id
        WHERE t.transaction_date >= NOW() - INTERVAL '3 days'
        GROUP BY c.country_code, c.mobile_number
        HAVING COUNT(t.id) >= 5
      `;

      this.logger.log({ count: suspects.length }, 'Forensic suspects found');

      const emailConfig = await this.prisma.emailConfig.findFirst({ where: { id: 1 } });

      for (const suspect of suspects) {
        try {
          // Check if alert already sent in last 24h
          const existingAlert = await this.prisma.forensicAlert.findFirst({
            where: {
              mobileNumber: suspect.mobile_number,
              alertDate: { gte: new Date(Date.now() - 86400000) },
            },
          });

          if (existingAlert) continue;

          const alert = await this.prisma.forensicAlert.create({
            data: {
              mobileNumber: suspect.mobile_number,
              transactionCount: suspect.tx_count,
              firstTransactionDate: suspect.first_tx_date,
              lastTransactionDate: suspect.last_tx_date,
              stores: suspect.stores ?? [],
              totalAmount: suspect.total_amount,
            },
          });

          // Send alert email
          if (emailConfig?.alertEmail && emailConfig.isActive) {
            const html = this.buildAlertEmailHtml(suspect);
            await this.email.sendAlertEmail(
              emailConfig.alertEmail,
              `🚨 Forensic Alert: Suspicious Activity — ${suspect.mobile_number}`,
              html,
            );

            await this.prisma.forensicAlert.update({
              where: { id: alert.id },
              data: { emailSent: true },
            });

            this.logger.log(
              {
                mobile: suspect.mobile_number,
                txCount: suspect.tx_count,
                totalAmount: suspect.total_amount,
                alertId: String(alert.id),
              },
              'Forensic alert email sent',
            );
          }
        } catch (err) {
          this.logger.error({ err, mobile: suspect.mobile_number }, 'Failed to process forensic suspect');
        }
      }
    } catch (err) {
      this.logger.error({ err, durationMs: Date.now() - start }, 'ForensicAlertJob failed');
    }

    this.logger.log({ job: 'ForensicAlertJob', durationMs: Date.now() - start }, 'Forensic alert job complete');
  }

  private buildAlertEmailHtml(suspect: {
    mobile_number: string;
    tx_count: number;
    first_tx_date: Date;
    last_tx_date: Date;
    stores: string[];
    total_amount: number;
  }): string {
    return `
      <h2 style="color:#dc2626">🚨 Suspicious Activity Detected</h2>
      <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif">
        <tr><th style="background:#f3f4f6">Mobile Number</th><td>${suspect.mobile_number}</td></tr>
        <tr><th style="background:#f3f4f6">Transaction Count (3 days)</th><td><strong>${suspect.tx_count}</strong></td></tr>
        <tr><th style="background:#f3f4f6">Total Amount</th><td>${suspect.total_amount.toFixed(2)}</td></tr>
        <tr><th style="background:#f3f4f6">First Transaction</th><td>${suspect.first_tx_date}</td></tr>
        <tr><th style="background:#f3f4f6">Last Transaction</th><td>${suspect.last_tx_date}</td></tr>
        <tr><th style="background:#f3f4f6">Stores</th><td>${(suspect.stores ?? []).join(', ')}</td></tr>
      </table>
      <p style="color:#6b7280;font-size:12px">Generated by LoyalArc Forensic Monitor — ${new Date().toISOString()}</p>
    `;
  }
}
