[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo run build --filter=@loyalty/api"]

[start]
cmd = "node apps/api/start.js"
